version: '3'

volumes:
  mirror-data:
    driver: local
    driver_opts:
        o: bind
        type: none
        device: ./mirror-server

services:
  http-server:
    volumes:
      - mirror-data:/mnt/mirror
    build:
      context: http
    ports:
      - "${MIRROR_PORT}:80"
    restart: on-failure
