name: WinConveyoR

on:
  push:
    branches-ignore:
      - 'ga-ignore-**'
  pull_request:
    branches-ignore:
      - 'ga-ignore-**'

env:
  BINARIES: "./cli/dist/wcr ./lib/libwconr/libwconr.so"

jobs:
  check_build:
    runs-on: ubuntu-latest

    if: ${{ github.event_name == 'push' }}

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install build tools
        run: sudo apt install -y gcc libc6-dev make python3 python3-pip

      - name: Install pyinstaller
        run: pip install pyinstaller

      - name: clean objects
        run: |
          make clean

      - name: compile project
        run: |
          chmod +x ./compile_linux.sh; ./compile_linux.sh

      - name: test file exist
        run: |
          for binary in $(echo "${{ env.BINARIES }}" | tr ',' ' '); do
            if [ ! "${binary}" ]; then
              echo "Binary ${binary} doesn't exist."
              exit 1
            fi
          done

      - name: remove caches
        run: make fclean
